name: xsd_to_dart_code
description: A library that lets you generate dart code (like classes and enums) from an XML Schema (like an xsd file).
version: 1.0.0
# repository: https://github.com/my_org/my_repo
publish_to: none  #FIXME this is for testing, remove line when using published dart_code package

environment:
  sdk: ^3.9.2


# Add regular dependencies here.
dependencies:
  change_case: ^2.2.0
  collection: ^1.19.1
  dart_code:
    path: ../dart_code #FIXME this is for testing, use published package later
  logging: ^1.3.0
  path: ^1.9.1
  plural_noun: ^0.2.1
  shouldly: ^0.5.0+1
  xml: ^6.6.1
  # path: ^1.8.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.0
